import { Metadata } from "next";
import PoemsPage from "./poems/page";

export const metadata: Metadata = {
  title: "Corina Nica",
  description: "Generated by create next app",
};

export default function Home() {
  return <PoemsPage />;
}
